name: MakiDesktop
description: Control a VNC server from Maps!
version: 1.0.1
api-version: 1.17
main: me.ayunami2000.MakiDesktop.MakiDesktop
commands:
  maki:
    description: Manage MakiDesktop
    usage: /<command>